server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: nest-microservices
    static_configs:
      - targets:
          - localhost
        labels:
          job: nest-microservices
          __path__: /var/log/nest-microservices/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            context: context
            traceId: traceId
      - timestamp:
          source: timestamp
          format: RFC3339
      - labels:
          level:
          context:
          traceId:
      - output:
          source: message
